#!/bin/sh

OWNCLOUD_VERSION=7.0.4
INSTALL_DIR="/home/owncloud/owncloud"

DATA_DIR="/home/owncloud/data"
LOG_DIR="/var/log/owncloud"

SETUP_DIR="/app/setup"

# add owncloud user
adduser --disabled-login --gecos 'Owncloud' owncloud 
passwd -d owncloud

# create symlink to ${DATA_DIR}/dotfiles/.ssh
rm -rf /home/owncloud/.ssh
sudo -u owncloud -H ln -s ${DATA_DIR}/dotfiles/.ssh /home/owncloud/.ssh

# Install Owncloud, use local copy if available
mkdir -p ${INSTALL_DIR} ${LOG_DIR} /var/log/cron

if [ -f ${SETUP_DIR}/owncloud-${OWNCLOUD_VERSION}.tar.bz2 ]
then
    tar -C ${INSTALL_DIR} -xvf ${SETUP_DIR}/owncloud-${OWNCLOUD_VERSION}.tar.bz2
else
    wget -nv "https://download.owncloud.org/community/owncloud-${OWNCLOUD_VERSION}.tar.bz2" -O /tmp/oc.tar.bz2
    tar -C ${INSTALL_DIR} -xvf /tmp/oc.tar.bz2
fi

# Fix permissions
chown -R owncloud:owncloud ${INSTALL_DIR}

# disable default nginx configuration
rm -f /etc/nginx/sites-enabled/default

# run nginx as owncloud user
sed 's/user www-data/user owncloud/' -i /etc/nginx/nginx.conf

# move supervisord.log file to ${LOG_DIR}/supervisor/
sed 's|^logfile=.*|logfile='"${LOG_DIR}"'/supervisor/supervisord.log ;|' -i /etc/supervisor/supervisord.conf

# move nginx logs to ${LOG_DIR}/nginx
sed 's|access_log /var/log/nginx/access.log;|access_log '"${LOG_DIR}"'/nginx/access.log;|' -i /etc/nginx/nginx.conf
sed 's|error_log /var/log/nginx/error.log;|error_log '"${LOG_DIR}"'/nginx/error.log;|' -i /etc/nginx/nginx.conf

# setup log rotation for owncloud application logs
cat > /etc/logrotate.d/owncloud <<EOF
${LOG_DIR}/owncloud/*.log {
  weekly
  missingok
  rotate 52
  compress
  delaycompress
  notifempty
  copytruncate
}
EOF

# setup log rotation for redmine vhost logs
cat > /etc/logrotate.d/owncloud-vhost <<EOF
${LOG_DIR}/nginx/*.log {
  weekly
  missingok
  rotate 52
  compress
  delaycompress
  notifempty
  copytruncate
}
EOF

# configure supervisord log rotation
cat > /etc/logrotate.d/supervisord <<EOF
${LOG_DIR}/supervisor/*.log {
  weekly
  missingok
  rotate 52
  compress
  delaycompress
  notifempty
  copytruncate
}
EOF

# configure supervisord to start nginx
cat > /etc/supervisor/conf.d/nginx.conf <<EOF
[program:nginx]
priority=20
directory=/tmp
command=/usr/sbin/nginx -g "daemon off;"
user=root
autostart=true
autorestart=true
stdout_logfile=${LOG_DIR}/supervisor/%(program_name)s.log
stderr_logfile=${LOG_DIR}/supervisor/%(program_name)s.log
EOF

# configure supervisord to start crond
cat > /etc/supervisor/conf.d/cron.conf <<EOF
[program:cron]
priority=20
directory=/tmp
command=/usr/sbin/cron -f
user=root
autostart=true
autorestart=true
stdout_logfile=${LOG_DIR}/supervisor/%(program_name)s.log
stderr_logfile=${LOG_DIR}/supervisor/%(program_name)s.log
EOF

# cleanup
rm -rf /var/lib/apt/lists/*

